import './globals.css'
import { Ubuntu } from 'next/font/google'

const ubuntu = Ubuntu ({ 
  weight: ['300', '400'],
  subsets: ['latin'] }
);


export const metadata = {
  title: 'devSupport',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={ubuntu.className}>{children}</body>
    </html>
  )
}
